<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="42137" started-at="2019-11-21T16:04:58Z" finished-at="2019-11-21T16:05:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="42137" started-at="2019-11-21T16:04:58Z" finished-at="2019-11-21T16:05:40Z">
      <class name="com.harmony.qa.tests.HomePageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.harmony.qa.tests.HomePageTest@598067a5]" name="setup" is-config="true" duration-ms="41903" started-at="2019-11-21T21:34:58Z" finished-at="2019-11-21T21:35:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyTrainingPage()[pri:0, instance:com.harmony.qa.tests.HomePageTest@598067a5]" name="verifyTrainingPage" duration-ms="8" started-at="2019-11-21T21:35:40Z" finished-at="2019-11-21T21:35:40Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[No enum constant com.harmony.qa.constants.Links.WellSky Training Site]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: No enum constant com.harmony.qa.constants.Links.WellSky Training Site
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.harmony.qa.constants.Links.valueOf(Links.java:1)
	at com.harmony.qa.pages.HomePage.navigationThroughChapters(HomePage.java:72)
	at com.harmony.qa.tests.HomePageTest.verifyTrainingPage(HomePageTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTrainingPage -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.harmony.qa.tests.HomePageTest@598067a5]" name="teardown" is-config="true" duration-ms="182" started-at="2019-11-21T21:35:40Z" finished-at="2019-11-21T21:35:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.harmony.qa.tests.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
